const express = require('express');
const router = express.Router();

// Static list of universities in Vietnam (manually provided)
const UNIVERSITIES = [
  'Đại học Quốc gia Hà Nội',
  'Đại học Quốc gia Thành phố Hồ Chí Minh',
  'Đại học Bách Khoa Hà Nội (Trường Đại học Bách Khoa - ĐHQG Hà Nội)',
  'Đại học Bách Khoa Thành phố Hồ Chí Minh',
  'Đại học Kinh tế Quốc dân',
  'Đại học Ngoại thương',
  'Đại học FPT',
  'Đại học Công nghệ - ĐHQG Hà Nội',
  'Đại học Khoa học Tự nhiên - ĐHQG Hà Nội',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQG Hà Nội',
  'Đại học Kinh tế - ĐHQG Hà Nội',
  'Đại học Luật Hà Nội',
  'Đại học Y Hà Nội',
  'Đại học Dược Hà Nội',
  'Đại học Nông Lâm Thành phố Hồ Chí Minh',
  'Đại học Sư phạm Hà Nội',
  'Đại học Sư phạm Thành phố Hồ Chí Minh',
  'Đại học Tôn Đức Thắng',
  'Đại học Cần Thơ',
  'Đại học Huế',
  'Học viện Tài chính',
  'Học viện Ngân hàng',
  'Học viện Công nghệ Bưu chính Viễn thông',
  'Đại học Thương mại',
  'Đại học Giao thông Vận tải',
  'Đại học Xây dựng',
  'Đại học Mỏ - Địa chất',
  'Đại học Khoa học và Công nghệ Hà Nội (USTH)',
  'Đại học Sư phạm Kỹ thuật Hà Nội',
  'Đại học Thủy lợi',
  'Đại Học Duy Tân',
  'Đại học Thương mại Hà Nội',
  'Đại học Điện Lực',
  'Đại học Công nghiệp Hà Nội',
  'Đại học Công nghiệp Thành phố Hồ Chí Minh',
  'Đại học Quốc tế - ĐHQG TP.HCM',
  'Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
  'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
  'Đại học Kinh tế - Luật - ĐHQG TP.HCM',
  'Đại học Y Dược Thành phố Hồ Chí Minh',
  'Đại học Văn Lang',
  'Đại học RMIT Việt Nam',
  'Đại học Quốc tế Hồng Bàng',
  'Đại học Hoa Sen',
  'Đại học Sài Gòn',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM',
  'Đại học Nha Trang',
  'Đại học Thái Nguyên',
  'Đại học Vinh',
  'Đại học Đà Nẵng',
  'Đại học Quy Nhơn',
  'Đại học Kinh tế TP.HCM',
  'Đại học Công Nghiệp Thực Phẩm TP.HCM',
  'Đại học Sư phạm Kỹ thuật TP.HCM',
  'Đại học Bạc Liêu',
  'Đại học An Giang',
  'Đại học Tây Nguyên',
  'Đại học Lâm Nghiệp',
  'Đại học Thái Bình',
  'Đại học Hải Phòng',
  'Đại học Khoa học - Đại học Huế',
  'Đại học Kinh tế Quốc dân Hà Nội',
  'Đại học Thương Mại Hà Nội',
  'Đại học Nguyễn Tất Thành',
  'Đại học Tài Nguyên và Môi Trường Hà Nội',
  'Đại học Tài Nguyên và Môi Trường TP.HCM',
  'Đại học Sư phạm Thể dục Thể thao Hà Nội',
  'Đại học Sư phạm Thể dục Thể thao TP.HCM',
  'Đại học Hàng Hải Việt Nam',
  'Đại học Thủy sản Nha Trang',
  'Đại học Kinh tế - Kỹ thuật Công nghiệp',
  'Đại học Lạc Hồng',
  'Đại học Công Nghệ Đông Á',
  'Đại học Công Nghệ Đồng Nai',
  'Đại học Công Nghệ Sài Gòn',
  'Đại học Sư phạm Kỹ thuật Vĩnh Long',
  'Đại học Cửu Long',
  'Đại học Thủ Dầu Một',
  'Đại học Bình Dương',
  'Đại học Tài chính - Marketing',
  'Đại học Khoa học Phòng cháy Chữa cháy (Học viện)',
  'Đại học Phòng cháy Chữa cháy',
  'Đại học Kiến trúc Hà Nội',
  'Đại học Kiến trúc Thành phố Hồ Chí Minh',
  'Đại học Mỹ thuật Việt Nam',
  'Đại học Mỹ thuật Công nghiệp',
  'Đại học Nghệ thuật - Đại học Huế',
  'Đại học Mỹ thuật TP.HCM',
  'Học viện Khoa học Quân sự',
  'Học viện Quân y',
  'Học viện An ninh Nhân dân',
  'Học viện Cảnh sát Nhân dân',
  'Học viện Quản lý Giáo dục',
  'Học viện Kỹ thuật Quân sự',
  'Học viện Hậu cần',
  'Đại học Kiểm sát Hà Nội',
  'Đại học Khoa học Xã hội và Nhân văn Hà Nội (Trường ĐH KHXH&NV)',
  'Đại học Thăng Long',
  'Đại học Công đoàn',
  'Đại học Công nghệ Giao thông Vận tải',
  'Đại học Công nghệ Sài Gòn',
  'Đại học Sư phạm Hà Nội 2',
  'Đại học Nội Vụ Hà Nội',
  'Đại học Nội Vụ TP.HCM',
  'Đại học Quốc tế - Đại học Quốc gia Hà Nội (Vietnam Japan University)',
  'Đại học Quốc tế RMIT',
  'Đại học Quốc tế - Đại học Quốc gia Hà Nội',
  'Đại học Công nghiệp Thực phẩm Hà Nội',
  'Đại học Công nghiệp Việt Hung',
  'Đại học Mở Hà Nội',
  'Đại học Mở Thành phố Hồ Chí Minh',
  'Đại học Kinh tế - Đại học Đà Nẵng',
  'Đại học Sư phạm Hà Nội – Cơ sở 2 (Hà Nam)',
  'Đại học Hồng Đức',
  'Đại học Hà Tĩnh',
  'Đại học Thái Nguyên - Khoa Quốc tế',
  'Đại học Phú Yên',
  'Đại học Bà Rịa - Vũng Tàu',
  'Đại học Đồng Tháp',
  'Đại học Sóc Trăng',
  'Đại học Trà Vinh',
  'Đại học An Ninh Nhân Dân',
  'Đại học Nguyễn Huệ (private)',
  'Đại học Sử phạm Kỹ thuật Nam Định',
  'Đại học Kỹ thuật - Công nghiệp',
  'Đại học Phòng Thương mại và Công nghiệp Việt Nam',
  'Đại học Quảng Nam',
  'Đại học Quảng Bình',
  'Đại học Quảng Trị',
  'Đại học Kon Tum',
  'Đại học Hà Nội (Trường Đại học Hà Nội)',
  'Đại học Nguyễn Tất Thành',
  'Đại học Khoa học và Công nghệ - Đại học Đà Nẵng',
  'Đại học Đông Á',
  'Đại học Công nghệ Thông tin và Truyền thông Thái Nguyên',
  'Đại học Sư phạm - Đại học Thái Nguyên',
  'Đại học Vạn Hạnh',
  'Đại học HUTECH (Đại học Công nghệ TP.HCM)',
  'Đại học Bình Dương',
  'Đại học Kinh tế Nghệ An',
  'Đại học Nông Lâm Thái Nguyên',
  'Đại học Tài chính - Kế toán',
  'Đại học Y Dược Thái Bình',
  'Đại học Y Dược Hải Phòng',
  'Đại học Điều Dưỡng Nam Định',
  'Đại học Yersin Đà Lạt',
  'Đại học Mỏ - Địa chất',
  'Đại học Sư phạm Kỹ thuật Nam Định',
  'Đại học Quốc tế Hồng Bàng',
  'Đại học Công nghệ và Quản lý Hữu Nghị',
  'Đại học Văn hóa Hà Nội',
  'Đại học Văn hóa TP.HCM',
  'Đại học Văn hóa Nghệ thuật Quân đội',
  'Đại học Kinh tế - Kỹ thuật Công nghiệp',
  'Đại học Thủ đô Hà Nội',
  'Đại học Công Nghiệp Hà Nội - Cơ sở 2',
  'Đại học Hùng Vương',
  'Đại học Tây Đô',
  'Đại học Thành Đông',
  'Đại học Thành Phố Buôn Ma Thuột',
  'Đại học Sư phạm Quốc gia TP.HCM',
  'Đại học Công nghệ Đồng Nai',
  'Đại học Kinh tế - Đại học Quốc gia Hà Nội',
  'Đại học Giao thông Vận tải - Cơ sở phía Nam',
  'Đại học Công nghiệp Vinh',
  'Đại học Công nghiệp Thái Nguyên',
  'Đại học Khoa học - Đại học Thái Nguyên',
  'Đại học Kiến trúc Đà Nẵng',
  'Đại học Sư phạm - Đại học Đà Nẵng',
  'Đại học Sư phạm Kỹ thuật Đà Nẵng',
  'Đại học Kỹ thuật Công nghiệp - Đại học Thái Nguyên',
  'Đại học Công Nghiệp Quảng Ninh',
  'Đại học Phạm Văn Đồng',
  'Đại học Thành Tây',
  'Đại học Tân Trào',
  'Đại học Hòa Bình',
  'Đại học Đại Nam',
  'Đại học Quảng Ninh',
  'Đại học Phú Thọ',
  'Đại học Vinh - Cơ sở Hà Tĩnh',
  'Đại học Nha Trang',
  'Đại học Sư phạm TP.HCM - Cơ sở Thủ Đức'
];

// GET / -> return the static list
router.get('/', (req, res) => {
  res.json(UNIVERSITIES.sort((a, b) => a.localeCompare(b, 'vi')));
});

module.exports = router;
